version: '3'

services:
    jibri:
        image: jitsi/jibri
        volumes:
            - ${CONFIG}/jibri:/config
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        # deploy:
        #   resources:
        #     limits:
        #       cpus: '0.60'
        #       memory: 120M
        #     reservations:
        #       cpus: '0.40'
        #       memory: 100M
        deploy:
            replicas: 3
        devices:
            - /dev/snd:/dev/snd
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - XMPP_DOMAIN
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_BREWERY_MUC
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDING_DIR
            - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
            - JIBRI_STRIP_DOMAIN_JID
            - JIBRI_LOGS_DIR
            - DISPLAY=:0
            - TZ
            - JIBRI_EXTERNAL_INSTANCE
        depends_on:
            - prosody
            - jicofo
        networks:
            meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
